#pragma once

namespace CMD {
    enum Type : unsigned short {
        CMD_TEST_CONNECT = 100,
        CMD_LIST_DRIVES  = 101,
        CMD_LIST_DIR     = 102,

        CMD_DOWNLOAD_START = 103,
        CMD_DOWNLOAD_CHUNK = 104,
        CMD_DOWNLOAD_END   = 105,

        CMD_MOUSE_MOVE  = 201,
        CMD_MOUSE_CLICK = 202,
        CMD_MOUSE_POSITION = 203,
        CMD_KEYBOARD_EVENT = 204,
        CMD_MOUSE_WHEEL = 205,

        CMD_SCREENSHOT_START = 301,
        CMD_SCREENSHOT_CHUNK = 302,
        CMD_SCREENSHOT_END   = 303,
        CMD_SCREEN_STREAM_START = 304,
        CMD_SCREEN_STREAM_FRAME_START = 305,
        CMD_SCREEN_STREAM_FRAME_CHUNK = 306,
        CMD_SCREEN_STREAM_FRAME_END = 307,
        CMD_SCREEN_STREAM_STOP = 308,
        CMD_SCREEN_STREAM_KEYFRAME_REQUEST = 309,
        
        CMD_ERROR        = 999
    };
}
